import { type Issue, type Severity, type Category, type IssueStatus } from "@/lib/types";

// ─── Mock Data — 18 issues around Mumbai Andheri/Bandra corridor ──────────────
export const MOCK_ISSUES: Issue[] = [
  {
    id: "ISS-001", lat: 19.1197, lng: 72.8468,
    category: "Pothole", severity: "critical",
    title: "Large pothole causing accidents",
    description: "A dangerous 2-foot deep pothole has formed near the Andheri station junction. Multiple two-wheelers have skidded. The asphalt has completely caved in following last week's rains. Immediate patching required.",
    ward: "Ward 12 — Andheri East", status: "In Progress",
    reportedAt: "2026-08-06T09:30:00Z", upvotes: 47,
    address: "S.V. Road, near Andheri Station, Andheri East", photoSeed: 42,
  },
  {
    id: "ISS-002", lat: 19.0544, lng: 72.8405,
    category: "Water Clogging", severity: "critical",
    title: "Severe waterlogging blocking traffic",
    description: "Knee-deep water accumulation at Turner Road junction for over 3 days. Storm drain appears blocked. Businesses, schools and residential societies severely affected. BMC crew not seen.",
    ward: "Ward 7 — Bandra West", status: "Verified",
    reportedAt: "2026-08-09T14:00:00Z", upvotes: 89,
    address: "Turner Road Junction, Bandra West", photoSeed: 15,
  },
  {
    id: "ISS-003", lat: 19.1176, lng: 72.9060,
    category: "Crack", severity: "critical",
    title: "Structural crack in footbridge",
    description: "Visible crack running 4 metres along the footbridge over Powai Lake approach. Bridge sways under load. Multiple residents have reported it but no action taken for 6 weeks.",
    ward: "Ward 23 — Powai", status: "Reported",
    reportedAt: "2026-08-10T11:15:00Z", upvotes: 63,
    address: "Hiranandani Gardens Footbridge, Powai", photoSeed: 78,
  },
  {
    id: "ISS-004", lat: 19.1075, lng: 72.8263,
    category: "Water Clogging", severity: "moderate",
    title: "Waterlogging near school gate",
    description: "Children have to wade through ankle-deep water every morning. Blocked drain near school entrance. The problem occurs every monsoon but no permanent fix has been done.",
    ward: "Ward 8 — Juhu", status: "In Progress",
    reportedAt: "2026-08-08T07:45:00Z", upvotes: 38,
    address: "JVPD Scheme School, Juhu", photoSeed: 22,
  },
  {
    id: "ISS-005", lat: 19.1320, lng: 72.8181,
    category: "Road Damage", severity: "moderate",
    title: "Road collapsed after pipeline work",
    description: "BMC pipeline repair work left without proper road restoration. Large depression in road surface, about 6 inches deep over 15 sq metres. Creates hazardous driving conditions at night.",
    ward: "Ward 31 — Versova", status: "Verified",
    reportedAt: "2026-08-07T16:00:00Z", upvotes: 29,
    address: "Versova Road near Andheri-Versova Link Road", photoSeed: 55,
  },
  {
    id: "ISS-006", lat: 19.1140, lng: 72.8557,
    category: "Pothole", severity: "resolved",
    title: "Pothole cluster patched — good work!",
    description: "Cluster of 5 potholes on D.N. Nagar main road. Reported 12 days ago, BMC team arrived within 4 days and completed proper hot-mix patching. Road now smooth.",
    ward: "Ward 12 — Andheri East", status: "Resolved",
    reportedAt: "2026-07-31T10:00:00Z", upvotes: 21,
    address: "D.N. Nagar Main Road, Andheri West", photoSeed: 90,
  },
  {
    id: "ISS-007", lat: 19.0760, lng: 72.8777,
    category: "Crack", severity: "moderate",
    title: "Crumbling retaining wall on arterial road",
    description: "The retaining wall along the main road shows deep horizontal cracks and is bulging outward. Risk of partial collapse in heavy rain. Spans ~30 metres along the embankment.",
    ward: "Ward 15 — Dharavi", status: "Reported",
    reportedAt: "2026-08-11T08:00:00Z", upvotes: 55,
    address: "Dharavi Main Road, near 90 Feet Road", photoSeed: 33,
  },
  {
    id: "ISS-008", lat: 19.0663, lng: 72.8526,
    category: "Road Damage", severity: "critical",
    title: "Road surface completely destroyed",
    description: "Entire stretch of road (approx 200m) has broken up. No asphalt remaining, only loose gravel and potholes of varying sizes. Speed limit signs meaningless at this point.",
    ward: "Ward 10 — Sion", status: "Verified",
    reportedAt: "2026-08-05T13:00:00Z", upvotes: 102,
    address: "Dharavi-Sion Link Road, Sion", photoSeed: 67,
  },
  {
    id: "ISS-009", lat: 19.1663, lng: 72.8526,
    category: "Water Clogging", severity: "resolved",
    title: "Drain cleared, waterlogging fixed",
    description: "Chronic waterlogging at Goregaon market reported. BMC desilted the drain within 7 days. No waterlogging during last heavy rain on August 8th. Excellent response.",
    ward: "Ward 19 — Goregaon", status: "Resolved",
    reportedAt: "2026-07-25T09:00:00Z", upvotes: 18,
    address: "Goregaon West Market, Goregaon", photoSeed: 11,
  },
  {
    id: "ISS-010", lat: 19.1874, lng: 72.8481,
    category: "Pothole", severity: "moderate",
    title: "Multiple potholes near market",
    description: "Stretch of road near Malad market has developed 8-10 medium-sized potholes over the past 2 weeks. Heavy truck traffic appears to be worsening them daily.",
    ward: "Ward 21 — Malad West", status: "Reported",
    reportedAt: "2026-08-10T15:30:00Z", upvotes: 24,
    address: "Malad Market, S.V. Road, Malad West", photoSeed: 44,
  },
  {
    id: "ISS-011", lat: 19.2288, lng: 72.8566,
    category: "Other", severity: "moderate",
    title: "Damaged streetlights create dark stretch",
    description: "6 consecutive streetlights non-functional on Borivali main road. Stretch is completely dark after 8pm. Residents fear mugging. Multiple complaints made at ward office — no response.",
    ward: "Ward 25 — Borivali West", status: "Reported",
    reportedAt: "2026-08-09T20:00:00Z", upvotes: 41,
    address: "Borivali West Main Road, near IC Colony", photoSeed: 77,
  },
  {
    id: "ISS-012", lat: 19.0910, lng: 72.8650,
    category: "Pothole", severity: "critical",
    title: "Accident-prone pothole at crossroads",
    description: "Massive pothole at busy SEEPZ crossroads. Two accidents in past week, one resulting in hospitalization. Depth approximately 14 inches. Completely unmarked, no warning signs.",
    ward: "Ward 14 — Andheri East", status: "In Progress",
    reportedAt: "2026-08-08T11:00:00Z", upvotes: 73,
    address: "SEEPZ Crossroads, Andheri East", photoSeed: 59,
  },
  {
    id: "ISS-013", lat: 19.0399, lng: 72.8553,
    category: "Water Clogging", severity: "moderate",
    title: "Underpass floods in moderate rain",
    description: "The Mahim underpass floods to 2-3 feet depth even in moderate rainfall. Commuters stranded for hours. Pumping infrastructure seems non-functional.",
    ward: "Ward 6 — Mahim", status: "Verified",
    reportedAt: "2026-08-07T18:30:00Z", upvotes: 66,
    address: "Mahim Underpass, Western Express Highway", photoSeed: 31,
  },
  {
    id: "ISS-014", lat: 19.1057, lng: 72.8369,
    category: "Crack", severity: "resolved",
    title: "Bridge parapet repaired successfully",
    description: "Cracked parapet wall on the pedestrian bridge at Versova Link Road. Reported 3 weeks ago. BMC engineers inspected and repaired within agreed timeline. Citizens appreciate the response.",
    ward: "Ward 8 — Juhu", status: "Resolved",
    reportedAt: "2026-07-22T10:00:00Z", upvotes: 12,
    address: "Versova Link Road Bridge, Juhu", photoSeed: 83,
  },
  {
    id: "ISS-015", lat: 19.1445, lng: 72.8287,
    category: "Road Damage", severity: "moderate",
    title: "Service road completely broken up",
    description: "Service road parallel to Western Express Highway has disintegrated. Residents use it daily to access housing societies. BMC seems unaware as this is a disputed road asset.",
    ward: "Ward 16 — Oshiwara", status: "Reported",
    reportedAt: "2026-08-10T09:00:00Z", upvotes: 33,
    address: "WEH Service Road, Oshiwara, Andheri West", photoSeed: 68,
  },
  {
    id: "ISS-016", lat: 19.0839, lng: 72.8984,
    category: "Pothole", severity: "moderate",
    title: "School bus route pothole",
    description: "Two large potholes on the route used by school buses. Parents concerned about safety. School principal has written to BMC. No action for 2 weeks.",
    ward: "Ward 18 — Kurla", status: "Verified",
    reportedAt: "2026-08-06T08:00:00Z", upvotes: 48,
    address: "Kurla West Station Road, Kurla", photoSeed: 26,
  },
  {
    id: "ISS-017", lat: 19.0640, lng: 72.8350,
    category: "Water Clogging", severity: "critical",
    title: "Society basement flooded for 5 days",
    description: "Basement parking of Kalanagar society flooded due to broken drain. 45 cars submerged or damaged. BMC drain inspection team visited but no fix attempted. Citizens threatening legal action.",
    ward: "Ward 7 — Bandra East", status: "In Progress",
    reportedAt: "2026-08-07T10:00:00Z", upvotes: 91,
    address: "Kalanagar, Bandra East", photoSeed: 49,
  },
  {
    id: "ISS-018", lat: 19.1550, lng: 72.8710,
    category: "Other", severity: "resolved",
    title: "Manhole cover replaced — issue closed",
    description: "Missing manhole cover on Jogeshwari main road was a major safety hazard. Reported 10 days ago with photographic evidence. BMC replaced it within 5 days. Excellent turnaround.",
    ward: "Ward 17 — Jogeshwari", status: "Resolved",
    reportedAt: "2026-08-02T12:00:00Z", upvotes: 9,
    address: "Jogeshwari West Main Road", photoSeed: 71,
  },
];

// ─── Ward leaderboard for sidebar ────────────────────────────────────────────
export const WARD_LEADERBOARD = [
  { name: "Ward 12 — Andheri East", score: 94, delta: "+12%" },
  { name: "Ward 7 — Bandra West",   score: 87, delta: "+8%"  },
  { name: "Ward 23 — Powai",        score: 81, delta: "+21%" },
  { name: "Ward 31 — Versova",      score: 73, delta: "+5%"  },
  { name: "Ward 8 — Juhu",          score: 68, delta: "+3%"  },
  { name: "Ward 10 — Sion",         score: 61, delta: "-2%"  },
  { name: "Ward 17 — Jogeshwari",   score: 58, delta: "+9%"  },
];

// ─── Heatmap density points ───────────────────────────────────────────────────
export const HOTSPOT_DATA = [
  { lat: 19.1197, lng: 72.8468, intensity: 9 },
  { lat: 19.0544, lng: 72.8405, intensity: 8 },
  { lat: 19.0910, lng: 72.8650, intensity: 7 },
  { lat: 19.0640, lng: 72.8350, intensity: 8 },
  { lat: 19.1176, lng: 72.9060, intensity: 6 },
  { lat: 19.0760, lng: 72.8777, intensity: 5 },
  { lat: 19.0663, lng: 72.8526, intensity: 7 },
  { lat: 19.0399, lng: 72.8553, intensity: 5 },
];
